In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [3]:
a.ndim

1

In [4]:
a[0]

1

In [5]:
a[1]

2

In [6]:
a[0:2]

array([1, 2])

In [7]:
a[-1]

4

In [8]:
a[:]

array([1, 2, 3, 4])

In [9]:
a[:-1]

array([1, 2, 3])

In [10]:
a[-1:]

array([4])

In [11]:
a.itemsize

4

In [12]:
a.dtype

dtype('int32')

In [13]:
a.size

4

In [14]:
a.shape

(4,)

In [15]:
a.reshape(4,1)

array([[1],
       [2],
       [3],
       [4]])

In [16]:
a.ravel()

array([1, 2, 3, 4])

In [17]:
a.min()

1

In [18]:
a.max()

4

In [19]:
a.sum()

10

In [20]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [21]:
b=np.array([[1,2],[2,3],[3,4],[4,5]])
b

array([[1, 2],
       [2, 3],
       [3, 4],
       [4, 5]])

In [22]:
b.ndim

2

In [23]:
b[0]

array([1, 2])

In [24]:
b[-1]

array([4, 5])

In [25]:
b[0:3]

array([[1, 2],
       [2, 3],
       [3, 4]])

In [26]:
b.itemsize

4

In [27]:
b.dtype

dtype('int32')

In [28]:
b.size

8

In [29]:
b.shape

(4, 2)

In [30]:
b.reshape(2,4)

array([[1, 2, 2, 3],
       [3, 4, 4, 5]])

In [31]:
b.ravel()

array([1, 2, 2, 3, 3, 4, 4, 5])

In [32]:
b.min()

1

In [33]:
b.max()

5

In [34]:
b.sum()

24

In [35]:
b.sum(axis=0)

array([10, 14])

In [36]:
b.sum(axis=1)

array([3, 5, 7, 9])

In [37]:
np.sqrt(b)

array([[1.        , 1.41421356],
       [1.41421356, 1.73205081],
       [1.73205081, 2.        ],
       [2.        , 2.23606798]])

In [38]:
c=np.array([1,2,3,4,5,6,7,8],dtype='float')
c

array([1., 2., 3., 4., 5., 6., 7., 8.])

In [39]:
c.dtype

dtype('float64')

In [40]:
c.itemsize

8

In [41]:
c.size

8

In [42]:
c.shape

(8,)

In [43]:
c.reshape(8,1)

array([[1.],
       [2.],
       [3.],
       [4.],
       [5.],
       [6.],
       [7.],
       [8.]])

In [44]:
c.ravel()

array([1., 2., 3., 4., 5., 6., 7., 8.])

In [45]:
c.min()

1.0

In [46]:
c.max()

8.0

In [47]:
c.sum()

36.0

In [48]:
np.sqrt(c)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712])

In [49]:
d=np.array([[1,2,3],[4,5,6]],dtype='complex')
d

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]])

In [50]:
e=np.zeros((4,5))
e

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [51]:
f=np.ones((5,4))
f

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [52]:
f.ravel()

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [53]:
g=range(10)
g

range(0, 10)

In [54]:
g[0]

0

In [55]:
g[4]

4

In [56]:
g[6]

6

In [57]:
g[9]

9

In [58]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
np.linspace(2,5,10)

array([2.        , 2.33333333, 2.66666667, 3.        , 3.33333333,
       3.66666667, 4.        , 4.33333333, 4.66666667, 5.        ])

In [60]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [61]:
np.linspace(1,10,4)

array([ 1.,  4.,  7., 10.])

In [62]:
a=np.array([[1,2],[2,3],[3,4],[4,5]])
b=np.array([[5,6],[6,7],[7,8],[8,9]])

In [63]:
a+b

array([[ 6,  8],
       [ 8, 10],
       [10, 12],
       [12, 14]])

In [64]:
a-b

array([[-4, -4],
       [-4, -4],
       [-4, -4],
       [-4, -4]])

In [65]:
a*b

array([[ 5, 12],
       [12, 21],
       [21, 32],
       [32, 45]])

In [66]:
a/b

array([[0.2       , 0.33333333],
       [0.33333333, 0.42857143],
       [0.42857143, 0.5       ],
       [0.5       , 0.55555556]])